ALTER TABLE users
    ADD username VARCHAR(255) NULL;

ALTER TABLE users
    MODIFY email VARCHAR (255) NULL;

ALTER TABLE users
    MODIFY name VARCHAR (255) NULL;

ALTER TABLE users
    MODIFY password VARCHAR (255) NULL;

ALTER TABLE users
    MODIFY phone VARCHAR (255) NULL;